// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGnUm--xSp0lVI2CvziUgHPkFii6AZBs',
    appId: '1:51806915632:web:12b3a847281b324cc631f5',
    messagingSenderId: '51806915632',
    projectId: 'noti-ccf9c',
    authDomain: 'noti-ccf9c.firebaseapp.com',
    storageBucket: 'noti-ccf9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcM87Dj_zlzzKpQtA4H4GEh-HD6PvOtGQ',
    appId: '1:51806915632:android:ec240125697bed85c631f5',
    messagingSenderId: '51806915632',
    projectId: 'noti-ccf9c',
    storageBucket: 'noti-ccf9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJefVHmLZdWty2-iIRlKyMi-dSaGlSmA',
    appId: '1:51806915632:ios:f2e572e2a9b653bbc631f5',
    messagingSenderId: '51806915632',
    projectId: 'noti-ccf9c',
    storageBucket: 'noti-ccf9c.firebasestorage.app',
    iosBundleId: 'com.example.compound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJefVHmLZdWty2-iIRlKyMi-dSaGlSmA',
    appId: '1:51806915632:ios:f2e572e2a9b653bbc631f5',
    messagingSenderId: '51806915632',
    projectId: 'noti-ccf9c',
    storageBucket: 'noti-ccf9c.firebasestorage.app',
    iosBundleId: 'com.example.compound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdGnUm--xSp0lVI2CvziUgHPkFii6AZBs',
    appId: '1:51806915632:web:8c69459a1b4b93d2c631f5',
    messagingSenderId: '51806915632',
    projectId: 'noti-ccf9c',
    authDomain: 'noti-ccf9c.firebaseapp.com',
    storageBucket: 'noti-ccf9c.firebasestorage.app',
  );
}
